"""Initial migration

Revision ID: 6d64add7359c
Revises: 
Create Date: 2026-05-19 11:46:16.609083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d64add7359c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_tramite', sa.String(length=20), nullable=False),
    sa.Column('nombre_programa', sa.String(length=255), nullable=False),
    sa.Column('facultad', sa.String(length=255), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('modalidad', sa.String(length=100), nullable=True),
    sa.Column('lugar_desarrollo', sa.String(length=255), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expediente_id', 'numero')
    )
    op.create_table('campos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fase_id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fase_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('revisada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.UUID(), nullable=True),
    sa.Column('cambios', sa.JSON(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fase_id', sa.UUID(), nullable=False),
    sa.Column('campo_id', sa.UUID(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_storage', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campo_id'], ['campos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fase_id'], ['fases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias')
    op.drop_table('versiones')
    op.drop_table('observaciones')
    op.drop_table('campos')
    op.drop_table('fases')
    op.drop_table('expedientes')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###